backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Article Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Article Summary", name: "summary", widget: "text"}
      - {label: "Article Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "news"}

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Event Name", name: "title", widget: "string"}
      - {label: "Event Date", name: "event_date", widget: "datetime"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Event Description", name: "body", widget: "markdown"}
      - {label: "Booking Link", name: "booking_link", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "hidden", default: "events"}